'use strict';
var mongoose = require('mongoose');

var SurveyTemplateSchema = new mongoose.Schema({
    surveyName:     String,
    descr:          String,
    org:            {ref: String, orgName: String, picture: String},
    owner:          {ref: String, email: String, name: String, picture: String},
    tags:           [String],
    shareUrl:       String,
    isPublished:    {type: Boolean, default: false},
    isConcluded:    {type:Boolean, default:false}, //if the survey is concluded no future responses are accepted
    useCoupons:     {type: Boolean, default: false},
    coupons:        [String], //should be generated by the admin
    couponCriteria: {type: Number, default: 0}, //currently it simply the number of user-answers required for the coupon to flash
    noOfCouponsUsed: {type: Number, default: 0},
    noOfPackets:    Number,
    noOfQuesPerPacket: Number,
    noOfAnsPerQuestion: Number,
    packets:    [{
                    packetId: Number,
                    slides: [{
                        ques: String,
                        ans: String
                    }]
                }],
    metrics:    {
                    viewCount:      Number,
                    likes:          Number
                },
    template:   {
                    base:               {type:String, default:"styleHC"}, //this will hold the survey jade to be included
                    backgroundImage :   String,
                    logo:               String,
                    logoLink:           String,
                    locale:             {type:String, default:"english"},
                    showCatsInSlides :  {type:Boolean, default:"false"},
                    showIntro: {type:Boolean, default:true},
                    showInvite: {type:Boolean, default:true},
                    showTimeline: {type:Boolean, default:true},
                    showFaq: {type:Boolean, default:true},
                    hideProfile: {type:Boolean, default:false},
                    canAnswerAfterSubmission: {type:Boolean, default:false},
                    header: {
                        title:          String,
                        titleHelper:    String,
                        renderStyle: {
                            bkCol:      String,
                            col:        String,
                            font:       String
                                    }
                    },
                    intro:  {
                        showIntroVideo: {type:Boolean, default:true},
                        hideIntroNav:   {type:Boolean, default:false},
                        videoUrl:       String,
                        renderStyle: {
                            bkCol:      String,
                            col:        String,
                            font:       String
                                    },
                        sections: [
                            {
                                slides: [
                                    {
                                        title:  String,
                                        descr:  String,
                                        img:    String,
                                        next:   String
                                    }
                                ],
                                invite: {type:Boolean, default:false}
                            }
                        ],
                        loginText: {type:String, default: 'Login'}
                    },
                    invite: {
                        title:      String,
                        descr:      String,
                        email:      String,
                        password:   String,
                        htmlTop:    String,
                        htmlBottom: String,
                        subject:    String,
                        body:       String,
                        img:        String,
                        renderStyle: {
                            col:    String
                        }
                    },
                    faq: {
                        title:      String,
                        descr:      String,
                        renderStyle: {
                            col:    String
                        }
                    },
                    login: {
                        title:              String,
                        descr:              String,
                        usePassword:        {type:Boolean, default:false},
                        optInForEmail:      {type:Boolean, default:true},
                        isManualPrimary:    {type:Boolean, default:false},
                        password:           String,
                        useLogin:           Boolean,
                        useFBLogin:         Boolean,
                        useGoogLogin:       Boolean,
                        dataPolicy:         String,
                        termsOfUse:         String,
                        privacyPolicy:      String,
                        renderStyle: {
                            bkCol:      String,
                            col:        String,
                            font:       String
                                    }
                    },
                    profile: {
                        title:          String,
                        descr:          String,
                        renderStyle: {
                            col:    String
                        },
                        completeProfile:        Boolean,
                        showProfilePercent:     Boolean,
                        showMedia:              Boolean,
                        showSocial:             Boolean,
                        isExpandedProfile:      Boolean,
                        hideProfileOption:      Boolean,
                        instructions:           String,
                        twitterInstructions:    String,
                        instagramInstructions:  String,
                        mediaInstructions:      String,
                        socialHash:             String,
                        showReferral:           {type:Boolean, default: false},
                        mediaTags:              [String],
                        questions: [{
                                id:                     String,
                                categoryId:             String,
                                titleText:              String,
                                titleShortText:         String,
                                titleSubText:           String,
                                titleHelpText:          String,
                                renderType:             String, //radio, check, range, text
                                required:               {type:Boolean, default:true},
                                answerOptions:          {
                                                            rows: [{descr:String, value: String}],
                                                            cols: [{descr:String, value: String}]
                                                        },
                                dataHook:               {},     //writeback url
                                visible:                {type:Boolean, default:true},
                           }]
                    },
                    timeline: {
                        descr:          String,
                        renderStyle: {
                            col:        String
                        },
                        tooltips: {
                            groundwork: String,
                            survey:     String,
                            profile:    String,
                            invite:     String,
                            analysis:   String,
                            mapp:       String
                        }
                    },
                    thanks: {
                        title:          String,
                        descr:          String,
                        showProfileBtn: {type: Boolean, default: false},
                        img:            String,
                        renderStyle: {
                            bkCol:      String,
                            col:        String,
                            font:       String
                                    },
                        tooltips:[{
                            descr:      String
                        }],
                        gifts: [{
                            title:          String,
                            img:            String,
                            url:            String,
                            requirement:    String
                        }]
                    },
                    categories:[{
                                id:                     String,
                                title:                  String,
                                renderStyle:            {
                                                            col:     String,
                                                            bgCol:   String,
                                                            font1:   String,
                                                            font2:   String
                                                        },
                                visible:                {type:Boolean, default:true},
                                slideList:              [String]
                            }],
                    slides:  [{
                                id:                     String,
                                titleText:              String,
                                titleShortText:         String,
                                titleSubText:           String,
                                titleHelpText:          String,
                                renderType:             String, //radio, check, range, text
                                required:               {type:Boolean, default:true},
                                answerOptions:          {
                                                            rows: [{descr:String, value: String}],
                                                            cols: [{descr:String, value: String}]
                                                        },
                                dataHook:               {},     //writeback url
                                visible:                {type:Boolean, default:true},
                           }]
                },
    data: [{
            userToken: String,
            userResponses : [{slideNum:   Number, answer: String}]
          }],
    rawDataSetRef:  String,
    dateCreated:    {type: Date, default: Date.now},
    dateModified:   Date
});
var SurveyTemplateDB = mongoose.model('SurveyTemplate', SurveyTemplateSchema);

module.exports = SurveyTemplateDB;